### ISSUE TITLE
Explore use of Memo field in avalanche txn to carry useful data for us

### ISSUE THREAD

**Issue by gl-rockx** [AvaLido/mpc-controller#14]
The base tx in Avalanche has a Memo field (see [here](https://github.com/ava-labs/avalanchego/blob/620152091418f5dfdcf39e3bc4a86d5d45448280/vms/components/avax/base_tx.go#L32)) which can be used to carry arbitrary bytes. We can make use of it to carry some useful information.

One example is may be we can assign an id for each staking action we make and use it to track the history. It could help in cases where we need to support restaking (without moving tokens back and forth between C-Chain and P-Chain).

Using an id (e.g. of type uint64) can reduce the data required to identify the UTXOs.

**Comment by Zealy-Rockx** [comment]
Here are where we touched memo:
[ImportTx](https://github.com/AvaLido/mpc-controller/blob/utxo-memo/tasks/atomicTask/c2p/stake/txs.go#L255)
[AddDelegatorTx](https://github.com/AvaLido/mpc-controller/blob/utxo-memo/tasks/pChainTask/stake/addDelegatorTx.go#L115)
